import HeaderImage from '@/components/common/HeaderImage';
import '@/styles/globals.scss';
import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <div className="home-layout-container">
          <HeaderImage />
          <div className="home-layout-content">
            <h1 className="page-title">Agenda de Churras</h1>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
